# Generated by Django 3.2.9 on 2021-12-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('course_image', models.ImageField(upload_to='../images/')),
                ('deletion_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('zip_file', models.FileField(upload_to='../courses/')),
            ],
        ),
    ]
