# Generated by Django 3.2.9 on 2021-12-19 07:45

from django.db import migrations, models
import filebrowser.fields
import upload.storage


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Upload a video/image/swf, zipped slideshow, etc.', max_length=200, null=True, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(storage=upload.storage.OverwriteStorage(), upload_to='./images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='zip_file',
            field=models.FileField(upload_to='./courses/'),
        ),
    ]
